AWSTemplateFormatVersion: 2010-09-09
Parameters:
  # ALB
  IpAddressType:
    Type: String
    Default: ipv4
    AllowedValues: [ipv4, dualstack]
    ConstraintDescription: must be ipv4 or dualstack
  IdleTimeout:
    Type: String
    Default: 60
  ALBName:
    Type: String
  Scheme:
    Type: String
    Default: internet-facing
    AllowedValues: [internal, internet-facing]
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  ALBType:
    Type: String
    Default: application
    AllowedValues: [application, network]
    ConstraintDescription: must be application or network
  ALBTagName:
    Type: String

  # Security Group
  GroupName:
    Type: String
  GroupDescription:
    Type: String
  CidrIpEgress:
    Type: String
    Default: 0.0.0.0/0
  FromPortEgress:
    Type: String
  IpProtocolEgress:
    Type: String
    Default: -1
  ToPortEgress:
    Type: String
  CidrIpIngress:
    Type: String
    Default: 0.0.0.0/0
  FromPortIngress:
    Type: String
    Default: 22
  IpProtocolIngress:
    Type: String
    Default: tcp
  ToPortIngress:
    Type: Number
    Default: 22
  VpcId:
    Type: AWS::EC2::VPC::Id

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ALB
        Parameters:
          - ALBName
          - ALBType
          - IpAddressType
          - Scheme
          - Subnets
          - IdleTimeout
          - ALBTagName
          
      - Label: 
          default: Security Group
        Parameters:
          - GroupName
          - GroupDescription
          - VpcId
          - IpProtocolIngress
          - CidrIpIngress
          - FromPortIngress
          - ToPortIngress
          - IpProtocolEgress
          - CidrIpEgress
          - FromPortEgress
          - ToPortEgress

    ParameterLabels:
      ALBName:
        default: ALB Name
      ALBType:
        default: ALB Type
      IpAddressType:
        default: Ip Address Type
      Subnets:
        default: Subnet ID
      IdleTimeout:
        default: Idle Timeout
      ALBTagName:
        default: ALB Tag Name
      
      GroupName:
        default: Group Name
      GroupDescription:
        default: Group Description
      VpcId:
        default: Vpc ID
      IpProtocolIngress:
        default: Ip Protocol (Ingress)
      CidrIpIngress:
        default: CIDR Ip (Ingress)
      FromPortIngress:
        default: From Port (Ingress)
      ToPortIngress:
        default: To Port (Ingress)
      IpProtocolEgress:
        default: Ip Protocol (Egress)
      CidrIpEgress:
        default: CIDR Ip (Egress)
      FromPortEgress:
        default: From Port (Egress)
      ToPortEgress:
        default: To Port (Egress)

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: !Ref IpAddressType
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: !Ref IdleTimeout
      Name: !Ref ALBName
      Scheme: !Ref Scheme
      SecurityGroups:
        - !Ref SecurityGroup
      Type: !Ref ALBType


  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref GroupName
      GroupDescription: !Ref GroupDescription
      SecurityGroupEgress:
        - CidrIp: !Ref CidrIpEgress
          IpProtocol: !Ref IpProtocolEgress
          FromPort: !Ref FromPortEgress
          ToPort: !Ref ToPortEgress
      SecurityGroupIngress:
        - CidrIp: !Ref CidrIpIngress
          IpProtocol: !Ref IpProtocolIngress
          FromPort: !Ref FromPortIngress
          ToPort: !Ref ToPortIngress
      VpcId: !Ref VpcId